STOP REPLICA;
RESET REPLICA;
CHANGE MASTER TO
  MASTER_HOST='edu_rag_frps',
  MASTER_PORT=13306,
  MASTER_USER='root',
  MASTER_PASSWORD='123456',
  MASTER_LOG_FILE='binlog.000006',
  MASTER_LOG_POS=157;
START REPLICA;
SHOW REPLICA STATUS\G
